# This workflow build and push a Docker container to Google Artifact Registry
# and deploy it on Cloud Run when a PR to 'main' has been approved by a reviewer.

name: 'Build and Deploy to Cloud Run'
on:
  push:
    branches:
      - main
env:

  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  REGION: ${{ secrets.REGION_LOC_1 }}
  SERVICE: 'mrgn-service'
  IMAGE_NAME: 'mrgn-img'
  GCP_CREDENTIALS:  ${{ secrets.GCP_CREDENTIALS }}


jobs:
  
  deploy:
    runs-on: 'ubuntu-latest'

    environment:
      name: dev

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ env.GCP_CREDENTIALS }}'

      - name: Set Version
        run: |
          echo "VERSION=latest" >> $GITHUB_ENV

      - name: Generate .env.dev file
        run: |
          echo "placeholder=dev" > .env.dev
      
      - name: 'Docker Auth'
        run: |-
          gcloud auth configure-docker '${{ env.REGION }}-docker.pkg.dev'
          
      - name: 'Build Docker Image'
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          if [ -z "${{ env.PROJECT_ID }}" ]; then
            echo "Error: PROJECT_ID is not set."
            exit 1
          fi
          echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV
          docker build -t "${DOCKER_TAG}" --build-arg ENV=dev .

      - name: 'Push Docker Image'
        run: |-
          docker push "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          env_vars: VERSION=${{ env.VERSION }}