# This workflow builds and pushes a Docker container to Google Artifact Registry
# and deploys it to Cloud Run when a push to 'main' occurs.

name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  REGION: ${{ secrets.REGION_LOC_1 }}
  SERVICE: 'mrgn-service'
  IMAGE_NAME: 'mrgn-img'
  GCP_CREDENTIALS:  ${{ secrets.GCP_CREDENTIALS }}

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    environment:
      name: dev

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ env.GCP_CREDENTIALS }}'

      - name: 'Set Version'
        run: echo "VERSION=latest" >> $GITHUB_ENV

      - name: 'Generate .env.dev file'
        run: echo "placeholder=dev" > .env.dev

      - name: 'Docker Auth'
        run: gcloud auth configure-docker '${{ env.REGION }}-docker.pkg.dev'

      - name: 'Build Docker Image'
        run: |
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV
          docker build -t "${DOCKER_TAG}" --build-arg ENV=dev .

      - name: 'Push Docker Image'
        run: |
          docker push "${{ env.DOCKER_TAG }}"

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.DOCKER_TAG }}'
          env_vars: VERSION=${{ env.VERSION }}
